# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    env:
      POSTGRES_USER: testing-user
      POSTGRES_PASSWORD: postgres
      PORT: 8080
      HOSTNAME: http://localhost
      # The default PostgreSQL port
      POSTGRES_PORT: 5432
      # The hostname used to communicate with the PostgreSQL service container
      POSTGRES_HOST: postgres
      NODE_ENV: test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: testing-user
          POSTGRES_PASSWORD: postgres
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Create database
        run: npm run db:create
      - name: Migrate database
        run: npm run db:migrate
      - name: Run tests
        run: npm test
